### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yuuffff1212** [yuuffff1212/protospace-32631#1]
#URL
https://protospace-32631.herokuapp.com/

**Comment by hiraoka1102** [comment]
yuuffff1212さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

・ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できること
→ログアウト状態ではログインページしか見ることができませんでした

・投稿に必要な情報を入力すると、プロトタイプが編集できること
→編集ボタンを押そうとすると「We're sorry, but something went wrong.」といったページになりました

・ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること
→こちらひとまずログイン状態で試してみたところ、トップページのままで遷移することができませんでした

[修正箇所]
修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yuuffff1212** [comment]
ご確認ありがとうございます！

改めて修正致しましたので、挙動確認の程よろしくお願い致します！

**Comment by hiraoka1102** [comment]
yuuffff1212さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・投稿者は詳細ページからプロトタイプを削除できる
→削除ボタンを押すと「We’re sorry, but something went wrong.」と表示されました！

・ユーザーの詳細ページには、そのユーザーの詳細情報と、そのユーザーが投稿したプロトタイプが表示されている
→こちら投稿したはずの画像が表示されていませんでした、

・他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、
トップページにリダイレクトされる
→こちら他のユーザーの編集ページへ行くことができました

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yuuffff1212** [comment]
ご確認ありがとうございます。

修正箇所について１つ疑問点があるのですが、ローカルサーバーのほうで投稿の削除を選択すると正常に削除がされたので、今一度確認して頂いてもよろしいでしょうか？

**Comment by hiraoka1102** [comment]
ご連絡ありがとうございます！こちらslackにて別連絡させていただきますのでご確認をお願いいたします。

**Comment by yuuffff1212** [comment]
削除機能以外の実装も修正しましたので、ご確認よろしくお願い致します！

**Comment by hiraoka1102** [comment]
ありがとうございます。今確認したところ、2点修正が変わらずだったのですがこちらherokuへのpushはお済みでしょうか？

**Comment by yuuffff1212** [comment]
pushは完了しておりますが、反映されていないでしょうか？

**Comment by yuuffff1212** [comment]
私の方でも、本番環境で確認してみたところ動作がローカルサーバーでの挙動の通りに作動していないですね、

この場合は、本番環境でのプッシュが完了していないことが原因でしょうか？

**Comment by yuuffff1212** [comment]
close
